### ISSUE TITLE
Update Rails Version to 6.0

### ISSUE THREAD

**Issue by JosimarCamargo** [storyblok/rails-52-auth0#1]
**Problems to be solved**

- [x] Update the Rails version to 6.0
- [x] Update the Rails version on the documentation

**Comment by JosimarCamargo** [comment]
Hello kasirajr, thanks for the PR, 
I checked and there is still some references to Rails 5.2 in the https://github.com/storyblok/rails-52-auth0/blob/master/tutorial.md , could you update them as well? that would be great.

**Comment by kasirajr** [comment]
Hi @JosimarCamargo ,
I have updated the file. Please let me know if the changes are good to ship.

**Comment by JosimarCamargo** [comment]
Thanks again kasirajr
Looks good, soon will be merged
